const ACTIONS = {
   ADD_SHOPPE: 'ADD_SHOPPE',

   SET_USER: 'SET_USER',
   SET_COMMODITY: 'SET_COMMODITIES',
   SET_LABOR: 'SET_LABOR',

   SET_CURRENT_SHOPPE: 'SET_CURRENT_SHOPPE',
   SET_SHOPPES: 'SET_SHOPPES',
   SET_TAX_CHART: 'SET_TAX_CHART',

   SUBSCRIBE_SHOPPES: 'SUBSCRIBE_sHOPPES',
   SUBSCRIBE_TAXES: 'SUBSCRIBE_sHOPPES',

   LOAD_DATA: 'LOAD_DATA',

   NAVIGATE: 'NAVIGATE'
};

export default ACTIONS;
